### ISSUE TITLE
Issue in installing this package

### ISSUE THREAD

**Issue by bprasana** [Tabcorp/pgbouncer#3]
Exception: Call to 'pg_config --libdir' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:428:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.11-23.53.amzn1.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/node_modules/pgbouncer/node_modules/pg

i get this error when i run npm install pg_bouncer on linux. any thoughts

**Comment by rprieto** [comment]
Hi, this seems to be on AWS.
- what flavour of Linux is it?
- is `postgresql-dev` / `libpq-dev` installed?
- what's the output of `pg_config --libdir`?

Do you also get the same error if you try to `npm install pg`?
